apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-vk3s
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0052-tenant/tkrw-pr712-0075-0052-app/devfile-sample-vk3s@sha256:77d2e760dd003e09ce8f561e2a14637917c30c5bf6dca6bfcb14c75c8e8d5f4e
        name: my-nodejs
        resources: {}
status: {}
